USE ROLE SYSADMIN;
USE DATABASE KAGGLE_SUBSCRIPTION;
USE SCHEMA DBT_PJT;
-- GRANT PRIVILEGES TO SYSADMIN
GRANT CREATE VIEW ON SCHEMA DBT_PJT TO ROLE SYSADMIN;

-- SET UP THE WAREHOUSE  
CREATE OR ALTER WAREHOUSE PJT02_WH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  MAX_CLUSTER_COUNT = 1
  MIN_CLUSTER_COUNT = 1
  SCALING_POLICY = ECONOMY
  AUTO_SUSPEND = 600
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = FALSE 
  COMMENT = 'WAREHOUSE for prject02 monitoring revenue leakage. It has minimum size of spec'
  ENABLE_QUERY_ACCELERATION = FALSE
;

-- BASE ENVIRONMENT
USE WAREHOUSE PJT02_WH;
